apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartthings-exporter
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: smartthings-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smartthings-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartthings-exporter
    spec:
      containers:
      - env:
        - name: STE_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: api_token
              name: smartthings-exporter
        image: setheck/smartthings-exporter
        imagePullPolicy: IfNotPresent
        name: smartthings-exporter
        ports:
        - containerPort: 9119
          name: smartthings
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: smartthings
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 300
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 300
