---
kind: VMPodScrape
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: smartthings-exporter
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: smartthings-exporter
  podMetricsEndpoints:
    - port: smartthings
      path: /metrics
      relabelConfigs:
        - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
          action: replace
          targetLabel: instance
